### ISSUE TITLE
Bug: SIGSEGV on reading resp.Auth

### ISSUE THREAD

**Issue by muryoutaisuu** [Muryoutaisuu/secretsfs#47]
https://github.com/muryoutaisuu/secretsfs/blob/44bf2c025aea4d12ee17e5a5e70e984d1f4a7ed5/pkg/store/vault_kv.go#L265

```go
func VaultApproleLogin(c *api.Client, approleId string) (accessToken string, err error) {
	data := map[string]interface{}{
		"role_id": approleId,
	}
	resp, err := c.Logical().Write("auth/approle/login", data)
	if err != nil {
		return "", err
	}
	if resp.Auth == nil {
		return "", errors.New("no auth info returned")
	}
	return resp.Auth.ClientToken, nil
}
```

```bash
Aug 31 10:00:55 e1-bomc-alsu001 secretsfs[882035]: panic: runtime error: invalid memory address or nil pointer dereference
Aug 31 10:00:55 e1-bomc-alsu001 secretsfs[882035]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x8673aa]
Aug 31 10:00:55 e1-bomc-alsu001 secretsfs[882035]: goroutine 6 [running]:
Aug 31 10:00:55 e1-bomc-alsu001 secretsfs[882035]: github.com/muryoutaisuu/secretsfs/pkg/store.VaultApproleLogin(0xc0001d6b40, 0xc00024cba0, 0x24, 0x0, 0x0, 0x3, 0x7)
Aug 31 10:00:55 e1-bomc-alsu001 secretsfs[882035]: #011/home/runner/work/secretsfs/secretsfs/pkg/store/vault_kv.go:265 +0x10a
Aug 31 10:00:55 e1-bomc-alsu001 secretsfs[882035]: github.com/muryoutaisuu/secretsfs/pkg/store.GetClient(0xa0f718, 0xc00044c7e0, 0xc0008f85c8, 0x1, 0x1)
Aug 31 10:00:55 e1-bomc-alsu001 secretsfs[882035]: #011/home/runner/work/secretsfs/secretsfs/pkg/store/vault_kv.go:168 +0x13a
Aug 31 10:00:55 e1-bomc-alsu001 secretsfs[882035]: github.com/muryoutaisuu/secretsfs/pkg/store.getSecret(0xc0003393f0, 0x6, 0xa0f718, 0xc00044c7e0, 0x1, 0x1, 0xc0003393f0, 0x6)
Aug 31 10:00:55 e1-bomc-alsu001 secretsfs[882035]: #011/home/runner/work/secretsfs/secretsfs/pkg/store/vault_kv.go:46 +0x5cb
Aug 31 10:00:55 e1-bomc-alsu001 secretsfs[882035]: github.com/muryoutaisuu/secretsfs/pkg/store.(*VaultKv).GetSecret(0xcd8a10, 0xc0003393f0, 0x6, 0xa0f718, 0xc00044c7e0, 0x0, 0x0, 0x0)
Aug 31 10:00:55 e1-bomc-alsu001 secretsfs[882035]: #011/home/runner/work/secretsfs/secretsfs/pkg/store/vault_kv.go:30 +0x4e
Aug 31 10:00:55 e1-bomc-alsu001 secretsfs[882035]: github.com/muryoutaisuu/secretsfs/pkg/secretsfs.(*FIOSecretsFiles).Lookup(0xcd8a10, 0xc0002b8000, 0xa0f718, 0xc00044c7e0, 0xc0003393f0,
0x6, 0xc000413e48, 0x203000, 0x203000)
Aug 31 10:00:55 e1-bomc-alsu001 secretsfs[882035]: #011/home/runner/work/secretsfs/secretsfs/pkg/secretsfs/fio_secretsfiles.go:68 +0x3eb
Aug 31 10:00:55 e1-bomc-alsu001 secretsfs[882035]: github.com/muryoutaisuu/secretsfs/pkg/secretsfs.(*SfsNode).Lookup(0xc0002b8000, 0xa0f718, 0xc00044c7e0, 0xc0003393f0, 0x6, 0xc000413e48,
 0x0, 0x0)
Aug 31 10:00:55 e1-bomc-alsu001 secretsfs[882035]: #011/home/runner/work/secretsfs/secretsfs/pkg/secretsfs/sfsnode.go:197 +0xd02
Aug 31 10:00:55 e1-bomc-alsu001 secretsfs[882035]: github.com/hanwen/go-fuse/v2/fs.(*rawBridge).lookup(0xc000189400, 0xc00044c7e0, 0xc0002b8000, 0xc0003393f0, 0x6, 0xc000413e48, 0xc00045a
a80, 0xc000413f00)
Aug 31 10:00:55 e1-bomc-alsu001 secretsfs[882035]: #011/home/runner/go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.1.0/fs/bridge.go:340 +0x204
Aug 31 10:00:55 e1-bomc-alsu001 secretsfs[882035]: github.com/hanwen/go-fuse/v2/fs.(*rawBridge).Lookup(0xc000189400, 0xc00028fbc0, 0xc000413ed8, 0xc0003393f0, 0x6, 0xc000413e48, 0x8bdd00)
Aug 31 10:00:55 e1-bomc-alsu001 secretsfs[882035]: #011/home/runner/go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.1.0/fs/bridge.go:323 +0xd9
Aug 31 10:00:55 e1-bomc-alsu001 secretsfs[882035]: github.com/hanwen/go-fuse/v2/fuse.doLookup(0xc000186dc0, 0xc000413d40)
Aug 31 10:00:55 e1-bomc-alsu001 secretsfs[882035]: #011/home/runner/go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.1.0/fuse/opcode.go:333 +0x92
Aug 31 10:00:55 e1-bomc-alsu001 secretsfs[882035]: github.com/hanwen/go-fuse/v2/fuse.(*Server).handleRequest(0xc000186dc0, 0xc000413d40, 0xc000000000)
Aug 31 10:00:55 e1-bomc-alsu001 secretsfs[882035]: #011/home/runner/go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.1.0/fuse/server.go:483 +0x2b6
Aug 31 10:00:55 e1-bomc-alsu001 secretsfs[882035]: github.com/hanwen/go-fuse/v2/fuse.(*Server).loop(0xc000186dc0, 0x0)
Aug 31 10:00:55 e1-bomc-alsu001 secretsfs[882035]: #011/home/runner/go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.1.0/fuse/server.go:456 +0x198
Aug 31 10:00:55 e1-bomc-alsu001 secretsfs[882035]: github.com/hanwen/go-fuse/v2/fuse.(*Server).Serve(0xc000186dc0)
Aug 31 10:00:55 e1-bomc-alsu001 secretsfs[882035]: #011/home/runner/go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.1.0/fuse/server.go:378 +0x45
Aug 31 10:00:55 e1-bomc-alsu001 secretsfs[882035]: created by github.com/hanwen/go-fuse/v2/fs.Mount
Aug 31 10:00:55 e1-bomc-alsu001 secretsfs[882035]: #011/home/runner/go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.1.0/fs/mount.go:32 +0x108
```

**Comment by muryoutaisuu** [comment]
seems not to be related with sealed instances, those are logged accordingly:

```bash
time="2021-09-09T08:59:20+02:00" level=error msg="got error while getting vault client" func=github.com/muryoutaisuu/secretsfs/pkg/store.getSecret file="/appl/git/secretsfs/pkg/store/vault_kv.go:52" appendSubs=true error="Error making API request.\n\nURL: PUT http://127.0.0.1:8200/v1/auth/approle/login\nCode: 503. Errors:\n\n* Vault is sealed" pfclient="<nil>" spath=
time="2021-09-09T08:59:20+02:00" level=error msg="Got error while getting secret" func="github.com/muryoutaisuu/secretsfs/pkg/secretsfs.(*FIOSecretsFiles).Readdir" file="/appl/git/secretsfs/pkg/secretsfs/fio_secretsfiles.go:28" calling="sto.GetSecret(secpath, ctx)" error="Error making API request.\n\nURL: PUT http://127.0.0.1:8200/v1/auth/approle/login\nCode: 503. Errors:\n\n* Vault is sealed" secpath=
```
